## Updating Hitter and Pitcher Data to most recent player database

In [1]:
from pitch_functions import scrape_espn_player_data

Using TensorFlow backend.

In [10]:
import pandas as pd

In [12]:
pd.set_option('display.max_columns', None)

In [16]:
pd.set_option('display.max_row', 1000)

In [31]:
hitter_2019 = scrape_espn_player_data('http://www.espn.com/mlb/stats/batting/_/year/2019/count/{}/qualified/true')

In [32]:
hitter_2019.PLAYER.unique()

array(['Anthony Rendon', 'Tim Anderson', 'Christian Yelich',
       'DJ LeMahieu', 'Ketel Marte', 'Michael Brantley', 'Jeff McNeil',
       'Charlie Blackmon', 'Nolan Arenado', 'Rafael Devers',
       'Yoan Moncada', 'Whit Merrifield', 'Cody Bellinger',
       'Xander Bogaerts', 'Yuli Gurriel', 'J.D. Martinez', 'Jose Altuve',
       'Jorge Polanco', 'Freddie Freeman', 'Nelson Cruz', 'Trevor Story',
       'Juan Soto', 'Alex Bregman', 'Starling Marte', 'Ozzie Albies',
       'Trea Turner', 'George Springer', 'Mookie Betts',
       'Francisco Lindor', 'Mike Trout', 'Justin Turner', 'Wilson Ramos',
       'Austin Meadows', 'David Fletcher', 'Hunter Dozier', 'Kolten Wong',
       'Jose Iglesias', 'Amed Rosario', 'Cesar Hernandez',
       'Gleyber Torres'], dtype=object)

In [33]:
len(hitter_2019.PLAYER.unique())

40

In [3]:
pitcher_2019 = scrape_espn_player_data('http://www.espn.com/mlb/stats/pitching/_/year/2019/count/%7B%7D/qualified/false/order/false')

In [7]:
pitcher_2019.PLAYER.unique()

array(['Ian Kinsler', 'Russell Martin', 'Johnny Cueto', 'Sean Rodriguez',
       'Tommy Hunter', 'Pablo Sandoval', 'Ian Desmond', 'Gerardo Parra',
       'Charlie Culberson', 'Max Stassi', 'Caleb Joseph', 'JB Shuck',
       'Matt Moore', 'Dellin Betances', 'Jedd Gyorko', 'Bryan Holaday',
       'Jesus Sucre', 'Danny Hultzen', 'Xavier Cedeno', 'Aaron Loup',
       'Jose Peraza', 'Nate Karns', 'Jose Rondon', 'Kevin Plawecki',
       'Daniel Robertson', 'Luke Maile', 'Kyle Farmer', 'James Hoyt',
       'James Pazos', 'Matt Ramsey', "Ryan O'Rourke", 'AJ Reed',
       'Chris Ellis', 'Jacob Stallings', 'Taylor Davis', 'Donnie Hart',
       'Keynan Middleton', 'Nick Martini', 'Cole Sulser', 'Jose Castillo'],
      dtype=object)

Saving Data to CSV in ```Public Data``` Folder

In [6]:
hitter_2019_al = hitter_2019.sort_values(by='PLAYER')
hitter_2019_al

,RK,PLAYER,TEAM,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,AVG,OBP,SLG,OPS,WAR
193,,Aaron Wilkerson,MIL,3,1,1,0,0,1,2,0,0,0,1,.333,.333,1.333,1.667,0.1
73,,Aaron Wilkerson,MIL,3,1,1,0,0,1,2,0,0,0,1,.333,.333,1.333,1.667,0.1
33,,Aaron Wilkerson,MIL,3,1,1,0,0,1,2,0,0,0,1,.333,.333,1.333,1.667,0.1
633,,Aaron Wilkerson,MIL,3,1,1,0,0,1,2,0,0,0,1,.333,.333,1.333,1.667,0.1
553,,Aaron Wilkerson,MIL,3,1,1,0,0,1,2,0,0,0,1,.333,.333,1.333,1.667,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,,Wilmer Font,TOR/NYM/TB,3,0,1,0,0,0,0,0,0,0,2,.333,.333,.333,.667,0.1
546,,Wilmer Font,TOR/NYM/TB,3,0,1,0,0,0,0,0,0,0,2,.333,.333,.333,.667,0.1
226,,Wilmer Font,TOR/NYM/TB,3,0,1,0,0,0,0,0,0,0,2,.333,.333,.333,.667,0.1
626,,Wilmer Font,TOR/NYM/TB,3,0,1,0,0,0,0,0,0,0,2,.333,.333,.333,.667,0.1
346,,Wilmer Font,TOR/NYM/TB,3,0,1,0,0,0,0,0,0,0,2,.333,.333,.333,.667,0.1

In [14]:
len(hitter_2019['PLAYER'].unique())

40

In [9]:
pitcher_2019 = pitcher_2019.sort_values(by='PLAYER', ascending=True)
pitcher_2019

,RK,PLAYER,TEAM,GP,GS,IP,H,R,ER,BB,SO,W,L,SV,BLSV,WAR,WHIP,ERA
871,,AJ Reed,CHW,1,0,1.0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00
911,,AJ Reed,CHW,1,0,1.0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00
511,,AJ Reed,CHW,1,0,1.0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00
591,,AJ Reed,CHW,1,0,1.0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00
31,,AJ Reed,CHW,1,0,1.0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
578,,Xavier Cedeno,CHC,5,0,2.0,4,0,0,3,1,0,0,0,0,0.1,3.50,0.00
778,,Xavier Cedeno,CHC,5,0,2.0,4,0,0,3,1,0,0,0,0,0.1,3.50,0.00
18,,Xavier Cedeno,CHC,5,0,2.0,4,0,0,3,1,0,0,0,0,0.1,3.50,0.00
218,,Xavier Cedeno,CHC,5,0,2.0,4,0,0,3,1,0,0,0,0,0.1,3.50,0.00
538,,Xavier Cedeno,CHC,5,0,2.0,4,0,0,3,1,0,0,0,0,0.1,3.50,0.00

In [10]:
hitter_2019.to_csv(r"../public_data/hitter_data_2019.csv", index=False, sep=',', encoding='utf-8')

In [11]:
pitcher_2019.to_csv(r"../public_data/pitcher_data_2019.csv", index=False, sep=',', encoding='utf-8')