# Archived Files: Scraping Function can be found in pitch_functions

In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from bs4 import BeautifulSoup
import pandas as pd
import re
import os
import requests

## Hitter Dataframe Creation(consists of final batting stats from 2018 season)

In [2]:
url ='http://www.espn.com/mlb/stats/batting/_/year/2019/count/41/qualified/false'

page = requests.get(url)

soup = BeautifulSoup(page.text, 'html.parser')

### Populating a dataframe

In [3]:
header = soup.find('tr', attrs={'class': 'colhead'})

In [4]:
columns = [col.get_text() for col in header.find_all('td')]

In [5]:
final_df = pd.DataFrame(columns=columns)

In [6]:
final_df

Empty DataFrame
Columns: [RK, PLAYER, TEAM, AB, R, H, 2B, 3B, HR, RBI, SB, CS, BB, SO, AVG, OBP, SLG, OPS, WAR]
Index: []

In [9]:
# http://www.espn.com/mlb/stats/batting/_/year/2018/count/{}/qualified/false

In [16]:
# def scrape_espn_player_data(url):

#     '''This functions scrapes ESPN leaderboard data and returns a Pandas Data Frame'''
#     # Populate a dataframe
#     page = requests.get(url)
#     soup = BeautifulSoup(page.text, 'html.parser')
#     header = soup.find('tr', attrs={'class': 'colhead'})
#     columns = [col.get_text() for col in header.find_all('td')]
#     final_df = pd.DataFrame(columns=columns)

#     for i in range(1,1000, 40):
#         url =url.format(i)
#         page = requests.get(url)
#         soup = BeautifulSoup(page.text, 'html.parser')

#         players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
#         for player in players:
#             # Get Stat for each player
#             stats = [stat.get_text() for stat in player.find_all('td')]
#             # Create temp dataframe to add later
#             temp_df = pd.DataFrame(stats).transpose()
#             temp_df.columns = columns
#             # Add Data to final_df
#             final_df = pd.concat([final_df, temp_df], ignore_index=True)
#     return final_df

In [18]:
final_df = scrape_espn_player_data('http://www.espn.com/mlb/stats/batting/_/year/2018/count/{}/qualified/false')

AttributeError: 'NoneType' object has no attribute 'find_all'

In [ ]:
final_hitter_df = scrape_espn_player_data('http://www.espn.com/mlb/stats/batting/_/year/2018/count/%7B%7D/qualified/false', final_df)

### 2019 Full Hitters

In [4]:
final_hitting_19 = scrape_espn_player_data('http://www.espn.com/mlb/stats/batting/_/year/2019/count/%7B%7D/qualified/false')

In [5]:
final_hitting_19

,RK,PLAYER,TEAM,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,AVG,OBP,SLG,OPS,WAR
0,1,Francisco Liriano,PIT,1,0,1,0,0,0,0,0,0,1,0,1.000,1.000,1.000,2.000,0.1
1,,Will Smith,SF,1,0,1,0,0,0,2,0,0,0,0,1.000,1.000,1.000,2.000,0.1
2,,Oliver Drake,TB,1,0,1,0,0,0,1,0,0,0,0,1.000,1.000,1.000,2.000,0.1
3,,John Brebbia,STL,1,1,1,0,0,0,0,0,0,0,0,1.000,1.000,1.000,2.000,0.0
4,,Gregory Soto,DET,2,0,2,0,0,0,0,0,0,0,0,1.000,1.000,1.000,2.000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,,Kyle Lewis,SEA,6,2,2,0,0,2,4,0,0,0,1,.333,.333,1.333,1.667,0.0
996,,Ranger Suarez,PHI,3,0,1,0,0,0,0,0,0,0,2,.333,.333,.333,.667,0.0
997,,Ryan Helsley,STL,3,0,1,0,0,0,0,0,0,0,2,.333,.333,.333,.667,0.0
998,,Nico Hoerner,CHC,15,2,5,0,1,0,4,0,0,2,2,.333,.412,.467,.878,0.0
999,40,Anthony Rendon,WSH,493,109,164,41,3,32,114,3,1,62,76,.333,.415,.623,1.037,6.0

## Dataframe Creation

In [7]:
pitcher_url = 'http://www.espn.com/mlb/stats/pitching/_/count/196/qualified/false/order/false/minip/60'
# 'http://www.espn.com/mlb/stats/pitching/_/year/2018/qualified/false/order/false'
pitch_page = requests.get(pitcher_url)

soup1 = BeautifulSoup(pitch_page.text, 'html.parser')

In [8]:
header1 = soup1.find('tr', attrs={'class': 'colhead'})

In [9]:
columns1 = [col.get_text() for col in header1.find_all('td')]

In [10]:
pitch_final_df = pd.DataFrame(columns=columns1)
pitch_final_df

Empty DataFrame
Columns: [RK, PLAYER, TEAM, GP, GS, IP, H, R, ER, BB, SO, W, L, SV, BLSV, WAR, WHIP, ERA]
Index: []

In [11]:
for i in range(1,244, 40):
    url ='http://www.espn.com/mlb/stats/pitching/_/count/{}/qualified/false/order/false/minip/60'.format(i)
    #url1 = ''
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')

    players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
    for player in players:
        # Get Stat for each player
        stats = [stat.get_text() for stat in player.find_all('td')]
        # Create temp dataframe to add later
        temp_df1 = pd.DataFrame(stats).transpose()
        temp_df1.columns = columns1
        # Add Data to final_df
        pitch_final_df = pd.concat([pitch_final_df, temp_df1], ignore_index=True)
pitch_final_df

,RK,PLAYER,TEAM,GP,GS,IP,H,R,ER,BB,SO,W,L,SV,BLSV,WAR,WHIP,ERA
0,1,Liam Hendriks,OAK,69,2,79.1,56,14,14,21,115,4,2,22,5,3.6,0.97,1.59
1,2,Felipe Vazquez,PIT,56,0,60.0,43,12,11,13,90,5,1,28,3,2.9,0.93,1.65
2,3,Adam Ottavino,NYY,69,0,63.1,43,15,13,39,85,6,4,2,7,2.2,1.29,1.85
3,4,Brandon Workman,BOS,67,0,66.1,27,17,15,41,94,9,1,14,6,2.8,1.03,2.04
4,5,Emilio Pagan,TB,60,0,63.2,38,16,15,13,88,4,2,20,7,2.4,0.80,2.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,231,Jose Suarez,LAA,16,14,71.1,88,58,55,29,61,2,6,0,0,-0.9,1.64,6.94
231,232,Kyle Freeland,COL,20,20,99.1,120,84,77,38,78,3,11,0,0,-0.8,1.59,6.98
232,233,Peter Lambert,COL,18,18,86.1,113,69,67,35,54,3,6,0,0,-0.0,1.71,6.98
233,234,David Hess,BAL,21,14,77.0,94,72,63,28,66,1,10,0,0,-1.2,1.58,7.36
234,235,Edwin Jackson,DET/TOR,16,13,64.0,100,78,69,29,49,3,10,0,0,-2.4,2.02,9.70

In [12]:
final_2019_pdf = pitch_final_df

In [15]:
final_2019_pdf = final_2019_pdf.sort_values(by='PLAYER')

In [16]:
final_2019_pdf

,RK,PLAYER,TEAM,GP,GS,IP,H,R,ER,BB,SO,W,L,SV,BLSV,WAR,WHIP,ERA
219,220,Aaron Brooks,BAL/OAK,27,18,101.0,117,71,68,32,77,5,8,0,0,-0.5,1.48,6.06
8,9,Aaron Bummer,CHW,52,0,60.1,39,17,16,23,53,0,0,1,2,2.4,1.03,2.39
60,61,Aaron Nola,PHI,32,32,191.2,162,81,77,74,216,12,5,0,0,4.1,1.23,3.62
215,216,Aaron Sanchez,TOR/HOU,27,27,131.1,145,92,86,68,115,5,14,0,0,-0.2,1.62,5.89
2,3,Adam Ottavino,NYY,69,0,63.1,43,15,13,39,85,6,4,2,7,2.2,1.29,1.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,114,Zach Eflin,PHI,29,25,143.2,153,79,67,40,117,8,12,0,0,1.2,1.34,4.20
63,64,Zach Plesac,CLE,19,19,106.1,91,46,43,37,79,8,6,0,0,1.9,1.20,3.64
218,219,Zack Godley,TOR/ARI,33,9,92.0,96,62,61,42,70,4,5,2,0,-0.6,1.50,5.97
25,26,Zack Greinke,HOU/ARI,31,31,195.1,166,69,64,29,174,16,5,0,0,5.3,1.00,2.95
104,105,Zack Wheeler,NYM,29,29,180.1,184,88,82,49,179,11,7,0,0,3.0,1.29,4.09

In [29]:
final_2019_hdf = pitch_final_df

In [33]:
final_2019_hdf = final_2019_hdf.sort_values(by='PLAYER')

In [35]:
final_2019_hdf

,RK,PLAYER,TEAM,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,AVG,OBP,SLG,OPS,WAR
128,129,A.J. Pollock,LAD,274,46,72,14,1,14,42,4,1,23,67,.263,.329,.474,.803,0.4
101,102,Aaron Judge,NYY,345,67,94,16,0,23,50,3,2,60,125,.272,.384,.519,.903,4.7
120,121,Adalberto Mondesi,KC,387,56,103,18,9,9,57,39,6,17,120,.266,.293,.429,.722,2.4
68,69,Adam Eaton,WSH,517,96,146,24,7,14,46,13,3,59,96,.282,.367,.437,.804,1.6
69,70,Adam Frazier,PIT,512,74,144,30,7,9,47,4,4,36,68,.281,.338,.420,.757,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18,19,Yoan Moncada,CHW,464,75,143,29,4,23,72,10,3,39,139,.308,.363,.537,.900,3.8
185,186,Yolmer Sanchez,CHW,449,54,111,17,4,2,39,5,4,43,106,.247,.318,.316,.634,1.5
257,258,Yonder Alonso,CHW/COL,284,34,56,12,0,10,36,0,1,38,70,.197,.294,.345,.640,-0.9
15,16,Yordan Alvarez,HOU,279,53,88,23,0,25,75,0,0,48,81,.315,.417,.667,1.084,3.5
24,25,Yuli Gurriel,HOU,532,80,161,40,2,28,99,4,3,35,61,.303,.347,.543,.890,3.2

In [17]:
final_2019_pdf.to_csv(r"../public_data/pitcher_data_alpha.csv", index=False, sep=',', encoding='utf-8')

In [37]:
final_2019_hdf.to_csv(r"../public_data/hitter_data_alpha.csv", index=False, sep=',', encoding='utf-8')

In [34]:
len(final_2019_hdf.PLAYER.unique())

263

In [178]:
# final_hitter_df.to_csv(r"public_data/hitter_data.csv", index=False, sep=',', encoding='utf-8')

In [179]:
# pitch_final_df.to_csv(r'public_data/pitcher_data.csv', index=False, sep=',', encoding='utf-8')

In [ ]:
# for i in range(1,1000, 40):
#     url ='http://www.espn.com/mlb/stats/pitching/_/year/2018/count/{}/qualified/false/order/false'.format(i)
#     #url1 = ''
#     page = requests.get(url)
#     soup = BeautifulSoup(page.text, 'html.parser')

#     players = soup.find_all('tr', attrs={'class':re.compile('row player-10-')})
#     for player in players:
#         # Get Stat for each player
#         stats = [stat.get_text() for stat in player.find_all('td')]
#         # Create temp dataframe to add later
#         temp_df1 = pd.DataFrame(stats).transpose()
#         temp_df1.columns = columns1
#         # Add Data to final_df
#         pitch_final_df = pd.concat([pitch_final_df, temp_df1], ignore_index=True)
# pitch_final_df